# PostgreSQL Configuration (Render)

spring.datasource.url=jdbc:postgresql://dpg-d77qkc8gjchc73d40o9g-a.ohio-postgres.render.com:5432/n8n_formbased
spring.datasource.username=mayank
spring.datasource.password=smD7krglTO1Fx9iDLjmFGFTpeyFdp67w
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8000

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Configuration
jwt.secret=VGhpc0lzQVN0cm9uZ1NlY3JldEtleUZvckpXVEF1dGhUb2tlbkdlbmVyYXRpb24=
jwt.expiration-ms=86400000